import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync('index.html', 'utf8');
const app = fs.readFileSync('src/app.js', 'utf8');
const boardCss = fs.readFileSync('board-layout.css', 'utf8');
const hierarchyCss = fs.readFileSync('adventure-state-board.css', 'utf8');
const preparedCss = fs.readFileSync('prepared-play-board.css', 'utf8');
const polishCss = fs.readFileSync('workspace-polish.css', 'utf8');
const questCss = fs.readFileSync('quest-tracker.css', 'utf8');
const questJs = fs.readFileSync('quest-tracker.js', 'utf8');
const controls = fs.readFileSync('workspace-controls.js', 'utf8');
const initiative = fs.readFileSync('initiative-groups.js','utf8');

assert.match(html, /prepared-play-board-20260805/);
assert.match(html, /workspace-polish\.css/);
assert.match(html, /quest-tracker\.css/);
assert.match(html, /quest-tracker\.js/);
assert.match(html, /workspace-controls\.js/);
assert.match(html, /adventure-state-board\.css/);
assert.match(html, /prepared-play-board\.css/);
assert.doesNotMatch(html, /encounter-slot-guard/);
assert.match(html, /initiative-groups\.js\?v=rules-cards-1/);
assert.match(initiative, /living-table:rules-initiative/);
assert.doesNotMatch(html, /ROW BUILD 6/);
assert.match(app, /class="fixed-board"/);
assert.match(app, /class="board-slot slot-\$\{slot\.id\}"/);
assert.doesNotMatch(app, /<button class="stack-toggle"/);
assert.match(app, /<div class="stack-toggle" role="button"/);
assert.match(boardCss, /display:flex/);
assert.match(hierarchyCss, /flex-wrap: wrap !important/);
assert.match(hierarchyCss, /data-slot="location"/);
assert.match(hierarchyCss, /data-slot="site"/);
assert.match(hierarchyCss, /data-slot="room"/);
assert.doesNotMatch(hierarchyCss, /data-slot="scene"/);
assert.doesNotMatch(hierarchyCss, /data-slot="objective"/);
assert.match(hierarchyCss, /Immediate playable area/);
assert.match(preparedCss, /slot-heading::after/);
assert.match(preparedCss, /content:none!important/);
assert.match(polishCss, /workspace-panel-toggle/);
assert.match(controls, /observe\(app, \{ childList: true \}\)/);
assert.doesNotMatch(controls, /subtree:\s*true/);
assert.match(questCss, /single-card-holder > \.tarot-card/);
assert.doesNotMatch(questCss, /slot-objective/);
assert.match(questCss, /\.quest-row/);
assert.match(questJs, /main-quest/);
assert.match(questJs, /side-quest/);
assert.match(questJs, /data-add-side-quest/);
assert.match(questJs, /questState/);
assert.match(questJs, /state\.revealed/);

const slotDefinitions = [...app.matchAll(/id: "(location|site|room|npc|monster|hazard|treasure)"/g)].map(match => match[1]);
assert.deepEqual(slotDefinitions, ['location', 'site', 'room', 'npc', 'monster', 'hazard', 'treasure']);

console.log('The source board renders seven prepared-play slots while Scene, quests, and rules-driven grouped initiative retain separate state owners.');
