import assert from 'node:assert/strict';
import fs from 'node:fs';

const app = fs.readFileSync('src/app.js', 'utf8');
const schema = fs.readFileSync('src/schema.js', 'utf8');
const encounter = fs.readFileSync('src/encounter.js', 'utf8');
const wishingCake = fs.readFileSync('src/wishing-cake-cards.js', 'utf8');
const spatialCards = fs.readFileSync('src/wishing-cake-spatial-cards.js', 'utf8');
const cardPack = fs.readFileSync('src/wishing-cake-pack.js', 'utf8');
const modal = fs.readFileSync('card-modal.js', 'utf8');
const questTracker = fs.readFileSync('quest-tracker.js', 'utf8');

assert.match(schema, /LOCATION:"location"/);
assert.match(schema, /SITE:"site"/);
assert.match(schema, /ROOM:"room"/);
assert.match(schema, /SCENE:"scene"/);
assert.match(schema, /OBJECTIVE:"objective"/);
assert.match(app, /slot\.accepts\.includes\(card\.type\)/);
assert.match(app, /That card type does not belong in this slot/);
assert.match(app, /Track where the party is, what is happening now/);
assert.match(modal, /Open full card/);
assert.doesNotMatch(modal, /!event\.target\.closest\("\.stack-toggle"\)/);
assert.match(encounter, /wishingCakePackCards/);
assert.match(cardPack, /wishingCakeSpatialCards/);
assert.match(cardPack, /oldContextCardIds/);
assert.match(spatialCards, /The Wishing Cake Inn/);
assert.match(spatialCards, /Grand Celebration Hall/);
assert.match(spatialCards, /The Stolen Wish/);
assert.match(wishingCake, /openingDialogue/);
assert.match(wishingCake, /Birthday Spark Candle Tokens/);
assert.match(wishingCake, /uses: \{ max: 3, label: "candle tokens" \}/);
assert.match(wishingCake, /Healing Candy/);
assert.match(app, /usesRemaining/);
assert.match(app, /use-charge/);
assert.match(app, /restore-charge/);
assert.match(app, /DM FULL CARD/);
assert.match(app, /PLAYER CARD/);
assert.match(questTracker, /objectiveCards/);
assert.match(questTracker, /revealedQuests/);
assert.match(questTracker, /data-add-side-quest/);

console.log('Spatial cards, slot-linked cards, role-safe full cards, item uses, and quest tracking are protected.');
