import assert from 'node:assert/strict';
import fs from 'node:fs';
import { characterCards, findCharacterByImportCode, getCharacterProfile } from '../src/player/character-cards.js';
import { createInventory, deriveStats } from '../src/player/item-system.js';
import { abilityModifier, proficiencyBonus, spellSaveDc, spellAttackBonus, weaponAttackBonus, weaponDamageModifier } from '../src/dnd/rules-engine.js';

assert.equal(characterCards.length,6,'Wishing Cake playtest roster must contain six pregens');
assert.equal(new Set(characterCards.map(c=>c.id)).size,6);
const classes=new Set(characterCards.map(c=>getCharacterProfile(c,'2014').className));
for(const name of ['Fighter','Rogue','Wizard','Cleric','Ranger','Bard'])assert.equal(classes.has(name),true,`${name} pregen missing`);
const srd2024Backgrounds=new Set(['Acolyte','Criminal','Sage','Soldier']);
const codes=new Set();
for(const character of characterCards){
 assert.ok(fs.existsSync(`assets/characters/${character.id}.svg`),`${character.id} portrait is missing`);
 assert.ok(character.ownedItemIds.length>=2,`${character.id} needs owned gear`);
 for(const edition of ['dnd-2014','dnd-2024']){
  const profile=getCharacterProfile(character,edition);assert.equal(profile.level,3);assert.equal(proficiencyBonus(profile.level),2);assert.equal(profile.saveProficiencies.length,2);assert.equal(Array.isArray(profile.skillProficiencies),true);assert.equal(Array.isArray(profile.attacks),true);assert.equal(Array.isArray(profile.features),true);assert.equal(Array.isArray(profile.resources),true);assert.equal(typeof profile.maxHp,'number');assert.equal(typeof profile.initiative.modifier,'number');
  if(edition==='dnd-2024')assert.equal(srd2024Backgrounds.has(profile.background),true,`${character.id} uses a non-SRD 2024 background`);
  const code=character.back.importCodes[edition];assert.ok(code&&!codes.has(code),`${character.id} needs a unique ${edition} code`);codes.add(code);const found=findCharacterByImportCode(code);assert.equal(found.character.id,character.id);assert.equal(found.edition,edition);assert.match(character.back.qrPaths[edition],new RegExp(`character=${character.id}`));
  for(const attack of profile.attacks){assert.doesNotMatch(attack.damageDice,/d20/i);assert.equal(Number.isFinite(weaponAttackBonus(profile,attack)),true);assert.equal(Number.isFinite(weaponDamageModifier(profile,attack)),true);}
  const d=profile.spellDetails;assert.ok(d,'Every profile must explicitly define its spell sections');for(const key of ['cantrips','known','prepared','alwaysPrepared','spellbook','origin','lineage'])assert.equal(Array.isArray(d[key]),true,`${character.id} ${edition} missing ${key}`);
  if(profile.spellcastingAbility){const expectedAttack=proficiencyBonus(profile.level)+abilityModifier(profile.abilities[profile.spellcastingAbility]);assert.equal(spellAttackBonus(profile),expectedAttack);assert.equal(spellSaveDc(profile),8+expectedAttack);assert.ok(Object.keys(profile.spellSlots).length>0);}
  const stats=deriveStats({edition,equipped:{...character.startingEquipment}},createInventory(character.ownedItemIds),character);assert.equal(stats.maxHp,profile.maxHp);assert.ok(stats.ac>=10);if(character.startingEquipment.mainHand)assert.ok(stats.attackProfile,`${character.id} front needs its real equipped attack`);
 }
}
const expectedAc={'wendy-birthday-hero':16,'merrin-thief':14,'elara-evoker':12,'brunna-life-cleric':18,'fern-hunter':16,'lute-lore-bard':13};
for(const character of characterCards){for(const edition of ['2014','2024']){const stats=deriveStats({edition,equipped:{...character.startingEquipment}},createInventory(character.ownedItemIds),character);assert.equal(stats.ac,expectedAc[character.id],`${character.id} ${edition} printed-card AC must match starting equipment`);}}
const rogue=characterCards.find(c=>c.id==='merrin-thief');assert.equal(weaponAttackBonus(getCharacterProfile(rogue,'2014'),getCharacterProfile(rogue,'2014').attacks[0]),5);assert.equal(getCharacterProfile(rogue,'2024').features.some(f=>f.name==='Steady Aim'),true);assert.deepEqual(getCharacterProfile(rogue,'2024').tools,['Thieves’ Tools']);assert.equal(getCharacterProfile(rogue,'2024').weaponProficiencies.includes('Martial weapons with the Finesse or Light property'),true);
const ranger=characterCards.find(c=>c.id==='fern-hunter');assert.equal(weaponAttackBonus(getCharacterProfile(ranger,'2014'),getCharacterProfile(ranger,'2014').attacks[0]),7);assert.equal(getCharacterProfile(ranger,'2024').background,'Soldier');assert.equal(getCharacterProfile(ranger,'2024').speed,35);assert.equal(getCharacterProfile(ranger,'2024').skillProficiencies.includes('insight'),true,'Wood Elf Keen Senses must add a distinct skill');assert.deepEqual(getCharacterProfile(ranger,'2024').spellDetails.prepared,['Cure Wounds','Goodberry','Ensnaring Strike','Fog Cloud']);assert.equal(getCharacterProfile(ranger,'2024').spellDetails.alwaysPrepared.length,1);
const cleric=characterCards.find(c=>c.id==='brunna-life-cleric');assert.deepEqual(getCharacterProfile(cleric,'2014').abilities,{strength:14,dexterity:10,constitution:14,intelligence:8,wisdom:16,charisma:10});assert.deepEqual(getCharacterProfile(cleric,'2024').abilities,{strength:13,dexterity:10,constitution:14,intelligence:8,wisdom:16,charisma:12});assert.equal(getCharacterProfile(cleric,'2024').maxHp,27);assert.equal(getCharacterProfile(cleric,'2014').features.some(f=>f.name==='Bonus Proficiency'),true);assert.equal(getCharacterProfile(cleric,'2024').spellDetails.prepared.length,6);assert.equal(getCharacterProfile(cleric,'2024').spellDetails.alwaysPrepared.length,4);
const wizard=characterCards.find(c=>c.id==='elara-evoker');assert.equal(getCharacterProfile(wizard,'2014').spellDetails.spellbook.length,10);assert.equal(getCharacterProfile(wizard,'2024').spellDetails.prepared.length,6);
const bard=characterCards.find(c=>c.id==='lute-lore-bard');assert.equal(getCharacterProfile(bard,'2024').background,'Acolyte');assert.deepEqual(getCharacterProfile(bard,'2024').originFeats,['Magic Initiate (Cleric)','Skilled']);assert.equal(getCharacterProfile(bard,'2014').spellDetails.known.length,6);assert.equal(getCharacterProfile(bard,'2024').spellDetails.prepared.length,6);assert.equal(bard.startingEquipment.mainHand,'dagger');
const fighter=characterCards.find(c=>c.id==='wendy-birthday-hero');assert.equal(weaponAttackBonus(getCharacterProfile(fighter,'2014'),getCharacterProfile(fighter,'2014').attacks[1]),7);
const playerReady=fs.readFileSync('player-ready.js','utf8');const pregenLoader=fs.readFileSync('pregen-character-loader.js','utf8');const sheet=fs.readFileSync('player-character-sheet.js','utf8');assert.match(playerReady,/living-table:character-loaded/);assert.match(playerReady,/resetForCharacter/);assert.match(playerReady,/createInventory\(character\.ownedItemIds\)/);assert.match(playerReady,/state\.equipped=\{\.\.\.character\.startingEquipment\}/);assert.match(pregenLoader,/startingStats/);assert.match(pregenLoader,/deriveStats/);assert.match(sheet,/Always Prepared/);assert.match(sheet,/Spellbook/);assert.match(sheet,/Background \/ Origin Magic/);
console.log('Six-pregen dual-edition SRD roster, accurate card fronts, structured spell records, import codes, portraits, species/background facts, and dynamic equipment doll passed.');
