import assert from 'node:assert/strict';
import fs from 'node:fs';

const player=fs.readFileSync('player-ready.js','utf8');
const itemSystem=fs.readFileSync('src/player/item-system.js','utf8');
const characters=fs.readFileSync('src/player/character-cards.js','utf8');
const css=fs.readFileSync('player-ready.css','utf8');
const sheetCss=fs.readFileSync('player-character-sheet.css','utf8');
const sheet=fs.readFileSync('player-character-sheet.js','utf8');
const html=fs.readFileSync('player.html','utf8');

assert.match(player,/itemCards, slotLabels, createInventory/);
assert.match(player,/resolveRequestedCharacter/);
assert.match(player,/let activeCharacter=resolveRequestedCharacter\(\)/);
assert.match(player,/createInventory\(activeCharacter\.ownedItemIds\)/);
assert.match(player,/resetForCharacter/);
assert.match(player,/createInventory\(character\.ownedItemIds\)/);
assert.match(player,/state\.equipped=\{\.\.\.character\.startingEquipment\}/);
assert.match(characters,/defaultCharacterCard/);
assert.match(characters,/profiles:/);
assert.match(characters,/characterCards = Object\.freeze\(\[wendy, \.\.\.additionalPregens\]\)/);
assert.match(itemSystem,/export const characterCard=defaultCharacterCard/);
assert.match(player,/complete rules sheet/i);
assert.match(player,/deriveStats/);
assert.match(itemSystem,/effects:/);
for(const slot of ['mainHand','offHand','ring1','ring2','wondrous'])assert.match(itemSystem,new RegExp(slot));
for(const control of ['data-equipment-slot','data-auto-equip','data-unequip-item','data-read-item','data-use-item'])assert.match(player,new RegExp(control));
assert.match(player,/charges/);
assert.match(css,/\.rpg-paper-doll/);assert.match(css,/\.rpg-silhouette/);assert.match(css,/\.rpg-slot/);assert.match(css,/\.derived-stat-strip/);assert.match(css,/\.equipment-card/);
assert.match(sheetCss,/\.full-character-sheet/);
for(const section of ['Saving Throws','Skills','Equipment & Backpack','Always Prepared','Spellbook'])assert.match(sheet,new RegExp(section));
assert.match(html,/player-ready\.css/);assert.match(html,/player-ready\.js/);assert.match(html,/player-character-sheet\.css\?v=character-sheet-1/);assert.match(html,/player-character-sheet\.js\?v=character-sheet-1/);
console.log('Dynamic pregen RPG equipment doll, owned inventory, legal slots, item effects, and full character-sheet layer passed.');
