import assert from 'node:assert/strict';
import fs from 'node:fs';

const player = fs.readFileSync('player-ready.js', 'utf8');
const itemSystem = fs.readFileSync('src/player/item-system.js', 'utf8');
const characters = fs.readFileSync('src/player/character-cards.js', 'utf8');
const css = fs.readFileSync('player-ready.css', 'utf8');
const sheetCss = fs.readFileSync('player-character-sheet.css','utf8');
const sheet = fs.readFileSync('player-character-sheet.js','utf8');
const html = fs.readFileSync('player.html', 'utf8');

assert.match(player, /import \{ characterCard, itemCards, slotLabels, createInventory/);
assert.match(player, /createInventory\(characterCard\.ownedItemIds\)/);
assert.match(characters, /defaultCharacterCard/);
assert.match(characters, /profiles:/);
assert.match(itemSystem, /export const characterCard = defaultCharacterCard/);
assert.match(player, /full rules-accurate character sheet/i);
assert.match(player, /deriveStats/);
assert.match(itemSystem, /effects:/);
assert.match(itemSystem, /mainHand/);
assert.match(itemSystem, /offHand/);
assert.match(itemSystem, /ring1/);
assert.match(itemSystem, /ring2/);
assert.match(itemSystem, /wondrous/);
assert.match(player, /data-equipment-slot/);
assert.match(player, /data-auto-equip/);
assert.match(player, /data-unequip-item/);
assert.match(player, /data-read-item/);
assert.match(player, /data-use-item/);
assert.match(player, /charges/);
assert.match(css, /\.rpg-paper-doll/);
assert.match(css, /\.rpg-silhouette/);
assert.match(css, /\.rpg-slot/);
assert.match(css, /\.derived-stat-strip/);
assert.match(css, /\.equipment-card/);
assert.match(sheetCss, /\.full-character-sheet/);
assert.match(sheet, /Saving Throws/);
assert.match(sheet, /Skills/);
assert.match(sheet, /Equipment & Backpack/);
assert.match(html, /player-ready\.css/);
assert.match(html, /player-ready\.js/);
assert.match(html, /player-character-sheet\.css\?v=character-sheet-1/);
assert.match(html, /player-character-sheet\.js\?v=character-sheet-1/);

console.log('RPG equipment doll, owned inventory, legal slots, item effects, and full character-sheet layer passed.');
