import assert from 'node:assert/strict';
import fs from 'node:fs';
import { rollDie, rollD20 } from '../src/dice.js';
import { COMMANDS, applyCommand, createInitialState, eventText } from '../src/state.js';
import { createRuinedChapelSession } from '../src/encounter.js';
import { projectSessionFor } from '../src/projection.js';
import { ROLES, validateCard, validateSession } from '../src/schema.js';
import { SOURCE_KINDS, primarySourceFor, sourceRegistry, validateSourceRegistry } from '../src/integrations/sourceRegistry.js';

const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
const stackCss=fs.readFileSync('compact-stacks.css','utf8');
const app=fs.readFileSync('src/app.js','utf8');
const vision=fs.readFileSync('docs/PRODUCT_VISION.md','utf8');
const mvp=fs.readFileSync('docs/MVP_SPEC.md','utf8');
const integrationLedger=fs.readFileSync('docs/DND_REPOSITORY_INTEGRATION.md','utf8');
const sequence=values=>{let index=0;return()=>values[index++];};

assert.equal(rollDie(20,()=>0),1); assert.equal(rollDie(20,()=>0.999999),20);
const advantage=rollD20('advantage',sequence([0.2,0.8])); assert.deepEqual(advantage.rolls,[5,17]); assert.equal(advantage.total,17);
const disadvantage=rollD20('disadvantage',sequence([0.2,0.8])); assert.equal(disadvantage.total,5);
assert.throws(()=>rollD20('incorrect'),/Unknown d20 roll mode/);

let state=createInitialState();
let result=applyCommand(state,{type:COMMANDS.ROLL_D20,mode:'advantage'},{random:sequence([0.1,0.9])}); state=result.state;
assert.equal(state.total,19); assert.equal(state.revision,1);
result=applyCommand(state,{type:COMMANDS.TOGGLE_CARD,key:'hazard'}); state=result.state; assert.equal(state.revealed.hazard,true);
result=applyCommand(state,{type:COMMANDS.END_TURN}); state=result.state; assert.equal(state.active,1); assert.match(eventText(state)[0],/Skeleton A/);
result=applyCommand(state,{type:COMMANDS.UNDO}); state=result.state; assert.equal(state.active,0); assert.equal(result.event.type,'COMMAND_UNDONE');

const session=createRuinedChapelSession(); validateSession(session);
const dm=session.participants.find(p=>p.role===ROLES.DM);
const player=session.participants.find(p=>p.role===ROLES.PLAYER);
const dmView=projectSessionFor(session,dm);
const playerView=projectSessionFor(session,player);
assert.equal(dmView.cards.length,9);
assert.equal(playerView.cards.length,7);
assert.ok(dmView.cards.find(card=>card.id==='priest').dmFace.hp===32);
assert.equal(playerView.cards.find(card=>card.id==='priest').dmFace,undefined);
assert.equal(playerView.cards.some(card=>card.id==='hazard'),false);
assert.equal(playerView.cards.some(card=>card.id==='treasure'),false);
assert.equal(playerView.cards.find(card=>card.id==='caretaker').face.openingDialogue.startsWith('Please'),true);
assert.equal(playerView.cards.find(card=>card.id==='lantern').face.knownEffect.includes('3 charges'),true);
assert.equal(playerView.actors.find(actor=>actor.id==='cult-priest').hp,undefined);
assert.equal(playerView.actors.find(actor=>actor.id==='lyria').hp.current,32);
assert.throws(()=>projectSessionFor(session,{id:'intruder',name:'Intruder',role:'player'}),/not seated/);
assert.throws(()=>validateCard({id:'bad'}),/title/);

assert.equal(validateSourceRegistry(sourceRegistry),true);
assert.equal(primarySourceFor(SOURCE_KINDS.RULES_CATALOG),'cbw29512/DungeonCards');
assert.equal(primarySourceFor(SOURCE_KINDS.CARD_PLATFORM),'cbw29512/DungeonCards');
assert.equal(sourceRegistry.some(source=>source.repository==='cbw29512/monstercardforge'),true);
assert.equal(sourceRegistry.some(source=>source.repository==='cbw29512/CharacterForge'),true);
assert.throws(()=>validateSourceRegistry([...sourceRegistry,sourceRegistry[0]]),/Duplicate source repository/);
assert.match(integrationLedger,/Do not maintain a second handwritten SRD spell or monster catalog/);
assert.match(integrationLedger,/DNDTeachingAdventureDemonsWrath/);
assert.match(integrationLedger,/DungeonMaps/);

assert.match(html,/compact-stacks\.css/);
assert.match(app,/DM View/); assert.match(app,/Player View/); assert.match(app,/projectSessionFor/);
assert.match(app,/Adventure Deck/); assert.match(app,/Card Master Board/); assert.match(app,/const SLOTS/);
assert.match(app,/Location/); assert.match(app,/Room \/ Scene/); assert.match(app,/NPCs/); assert.match(app,/Monsters/);
assert.match(app,/Traps \/ Hazards/); assert.match(app,/Objective \/ Quest/); assert.match(app,/Treasure \/ Rewards/);
assert.match(app,/stack-count/); assert.match(app,/data-toggle-stack/); assert.match(app,/data-card-roll/);
assert.match(app,/data-roll-all-monsters/); assert.match(app,/groupedInitiative/); assert.match(app,/Identical monsters share one initiative value/);
assert.match(app,/data-open-picker/); assert.match(app,/data-place-card/); assert.match(app,/draggable="true"/);
assert.match(app,/data-flip-card/); assert.match(app,/data-remove-instance/);
assert.match(css,/\.fixed-board/); assert.match(css,/\.board-slot/); assert.match(css,/\.tarot-card/); assert.match(css,/\.card-picker/);
assert.match(stackCss,/\.card-stack/); assert.match(stackCss,/\.stack-count/); assert.match(stackCss,/\.inside-card-rolls/); assert.match(stackCss,/\.stack-drawer/);
assert.match(vision,/server-side/i); assert.match(mvp,/complete D&D-style combat encounter/i);
console.log('The Living Table card slots, readable cards, item uses, grouped initiative, projections, and source registry passed.');
