import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const [html,css,js]=await Promise.all([readFile('index.html','utf8'),readFile('stack-drawer-layer.css','utf8'),readFile('stack-drawer-layer.js','utf8')]);
assert.match(html,/stack-drawer-layer\.css/);
assert.match(html,/stack-drawer-layer\.js/);
assert.match(css,/position:fixed!important/);
assert.match(css,/--stack-drawer-max-height/);
assert.match(js,/getBoundingClientRect/);
assert.match(js,/rect\.bottom\+gap/);
assert.match(js,/dismissExpandedStack/);
assert.match(js,/event\.target\.closest\('\.card-stack,\.stack-drawer/);
assert.match(js,/toggle\?\.click\(\)/);
assert.match(js,/window\.addEventListener\('resize'/);
console.log('stack drawer layer tests passed');
