import { defaultCharacterCard } from "./character-cards.js";
import { ABILITIES, abilityModifier, proficiencyBonus, savingThrowModifier } from "../dnd/rules-engine.js";
export const characterCard=defaultCharacterCard;
const srd=item=>Object.freeze({source:"SRD",color:"srd-item",...item});
const custom=item=>Object.freeze({source:"Wishing Cake",color:"custom-item",...item});
const handSlots=Object.freeze(["mainHand","offHand"]);
const weapon=(id,name,image,attack,extra={})=>srd({id,name,category:"weapon",rarity:"standard",image,validSlots:[...handSlots],attunement:false,edition:"2014/2024",front:name,playerText:`${attack.damageDice} ${attack.damageType}; ${attack.range}.`,dmText:"Use the loaded character profile for proficiency, ability modifier, Fighting Style, and 2024 mastery.",attack,effects:[],...extra});
export const itemCards=Object.freeze([
 srd({id:"leather-armor",name:"Leather Armor",category:"armor",armorCategory:"Light armor",rarity:"standard",image:"🥋",validSlots:["armor"],attunement:false,edition:"2014/2024",front:"Supple leather armor",playerText:"AC 11 + Dexterity modifier.",dmText:"Light armor formula: 11 + Dexterity modifier.",donDoff:{"dnd-2014":{don:"1 minute",doff:"1 minute"},"dnd-2024":{don:"1 minute",doff:"1 minute"}},effects:[{kind:"armorFormula",base:11,dexCap:null}]}),
 srd({id:"scale-mail",name:"Scale Mail",category:"armor",armorCategory:"Medium armor",rarity:"standard",image:"🛡️",validSlots:["armor"],attunement:false,edition:"2014/2024",front:"Overlapping metal scales",playerText:"AC 14 + Dexterity modifier (maximum +2); disadvantage on Stealth.",dmText:"Medium armor formula: 14 + Dexterity modifier, maximum +2.",donDoff:{"dnd-2014":{don:"5 minutes",doff:"1 minute"},"dnd-2024":{don:"5 minutes",doff:"1 minute"}},effects:[{kind:"armorFormula",base:14,dexCap:2},{kind:"trait",label:"Disadvantage: Stealth while wearing Scale Mail"}]}),
 srd({id:"chain-mail",name:"Chain Mail",category:"armor",armorCategory:"Heavy armor",strengthRequirement:13,rarity:"standard",image:"⛓️",validSlots:["armor"],attunement:false,edition:"2014/2024",front:"Interlocking heavy mail",playerText:"AC 16; Strength 13; disadvantage on Stealth. Speed -10 ft. if Strength is below 13.",dmText:"Heavy armor sets AC to 16; Dexterity does not modify it. Strength below 13 reduces Speed by 10 ft.",donDoff:{"dnd-2014":{don:"10 minutes",doff:"5 minutes"},"dnd-2024":{don:"10 minutes",doff:"5 minutes"}},effects:[{kind:"armorFormula",base:16,dexCap:0},{kind:"trait",label:"Disadvantage: Stealth while wearing Chain Mail"}]}),
 srd({id:"shield",name:"Shield",category:"shield",armorCategory:"Shields",rarity:"standard",image:"🛡️",validSlots:[...handSlots],attunement:false,edition:"2014/2024",front:"A sturdy shield",playerText:"Uses one hand. +2 AC while properly used; 2024 requires Shield training for the AC benefit.",dmText:"2014: don/doff takes 1 Action. 2024: Utilize Action to don/doff; Shield training is required for +2 AC. Only one Shield can benefit/be wielded at a time.",donDoff:{"dnd-2014":{don:"1 Action",doff:"1 Action"},"dnd-2024":{don:"Utilize Action",doff:"Utilize Action"}},effects:[{kind:"add",target:"ac",value:2}]}),
 weapon("rapier","Rapier","🗡️",{kind:"melee",weaponGroup:"Martial weapons",attackAbility:"dexterity",damageDice:"1d8",damageType:"piercing",range:"5 ft.",properties:["finesse"],mastery2024:"Vex"}),
 weapon("rapier-plus-1","Rapier +1","⚔️",{kind:"melee",weaponGroup:"Martial weapons",attackAbility:"dexterity",damageDice:"1d8",damageType:"piercing",range:"5 ft.",properties:["finesse"],mastery2024:"Vex"},{rarity:"uncommon",playerText:"Magic rapier: +1 to attack and damage rolls.",dmText:"Add +1 to attack and damage rolls made with this weapon.",effects:[{kind:"add",target:"attack",value:1},{kind:"add",target:"damage",value:1}]}),
 weapon("shortsword","Shortsword","⚔️",{kind:"melee",weaponGroup:"Martial weapons",attackAbility:"dexterity",damageDice:"1d6",damageType:"piercing",range:"5 ft.",properties:["finesse","light"],mastery2024:"Vex"}),
 weapon("dagger","Dagger","🔪",{kind:"melee",weaponGroup:"Simple weapons",attackAbility:"dexterity",damageDice:"1d4",damageType:"piercing",range:"5 ft. / 20/60 ft.",properties:["finesse","light","thrown"],mastery2024:"Nick"}),
 weapon("mace","Mace","🔨",{kind:"melee",weaponGroup:"Simple weapons",attackAbility:"strength",damageDice:"1d6",damageType:"bludgeoning",range:"5 ft.",properties:[],mastery2024:"Sap"}),
 weapon("longbow","Longbow","🏹",{kind:"ranged",weaponGroup:"Martial weapons",attackAbility:"dexterity",damageDice:"1d8",damageType:"piercing",range:"150/600 ft.",properties:["ammunition","heavy","two-handed"],mastery2024:"Slow"}),
 weapon("shortbow","Shortbow","🏹",{kind:"ranged",weaponGroup:"Simple weapons",attackAbility:"dexterity",damageDice:"1d6",damageType:"piercing",range:"80/320 ft.",properties:["ammunition","two-handed"],mastery2024:"Vex"}),
 srd({id:"cloak-protection",name:"Cloak of Protection",category:"wondrous",rarity:"uncommon",image:"🧥",validSlots:["shoulders"],attunement:true,edition:"2014/2024",front:"A warding cloak",playerText:"While wearing and attuned, gain +1 AC and +1 to all saving throws.",dmText:"Requires attunement; +1 AC and +1 to all saves.",effects:[{kind:"add",target:"ac",value:1},{kind:"allSaves",value:1}]}),
 srd({id:"ring-protection",name:"Ring of Protection",category:"ring",rarity:"rare",image:"💍",validSlots:["ring1","ring2"],attunement:true,edition:"2014/2024",front:"A protective ring",playerText:"While wearing and attuned, gain +1 AC and +1 to all saving throws.",dmText:"Requires attunement; +1 AC and +1 to all saves.",effects:[{kind:"add",target:"ac",value:1},{kind:"allSaves",value:1}]}),
 srd({id:"boots-elvenkind",name:"Boots of Elvenkind",category:"wondrous",rarity:"uncommon",image:"🥾",validSlots:["feet"],attunement:false,edition:"2014/2024",front:"Silent elven boots",playerText:"Your steps make no sound, and you have advantage on Dexterity (Stealth) checks.",dmText:"No Speed increase; track silent steps and Stealth advantage.",effects:[{kind:"trait",label:"Silent steps"},{kind:"advantage",target:"stealth"}]}),
 srd({id:"potion-healing",name:"Potion of Healing",category:"potion",rarity:"common",image:"🧪",validSlots:[],attunement:false,edition:"2014/2024",front:"A red healing draught",playerText:"Regain 2d4 + 2 HP. Drink/administer: Action (2014), Bonus Action (2024).",dmText:"2014 potion use takes an Action. 2024 drinking or administering a Potion of Healing takes a Bonus Action.",useActionByEdition:{"dnd-2014":"Action","dnd-2024":"Bonus Action"},consumable:{count:2,healing:"2d4+2"},effects:[]}),
 custom({id:"birthday-spark",name:"Birthday Spark Candle",category:"wondrous",rarity:"story",image:"🕯️",validSlots:["wondrous"],attunement:false,edition:"Adventure",front:"A warm candle-flame token",playerText:"After a failed check, spend one charge to add 1d4 to the roll.",dmText:"Adventure-specific story item. Three charges; refresh all charges in the Cake Chamber.",uses:{max:3,current:3,recharge:"Cake Chamber"},effects:[]}),
 custom({id:"keeper-crown",name:"Keeper of the Wish Crown",category:"wondrous",rarity:"story",image:"👑",validSlots:["head"],attunement:false,edition:"Adventure",front:"A paper crown marked KEEPER OF THE WISH",playerText:"Narrative item; no numerical bonus.",dmText:"Do not modify ability scores, saves, AC, attacks, or damage.",effects:[{kind:"trait",label:"Birthday heart"}]})
]);
export const slotLabels=Object.freeze({head:"Head",neck:"Neck",shoulders:"Shoulders",armor:"Armor",hands:"Gloves / Gauntlets",mainHand:"Hand 1",offHand:"Hand 2",ring1:"Ring 1",ring2:"Ring 2",feet:"Feet",wondrous:"Wondrous"});
export function createInventory(ownedIds=null){const allowed=ownedIds?new Set(ownedIds):null;return itemCards.filter(item=>!allowed||allowed.has(item.id)).map(item=>({...item,effects:item.effects.map(effect=>({...effect})),attack:item.attack?{...item.attack,properties:[...(item.attack.properties||[])]}:null,uses:item.uses?{...item.uses}:null,consumable:item.consumable?{...item.consumable}:null}));}
export function validSlots(item){return item?.validSlots??[];}
export function equippedItems(state,inventory){const ids=[...new Set(Object.values(state.equipped).filter(Boolean))];return ids.map(id=>inventory.find(item=>item.id===id)).filter(Boolean);}
export function attunementCount(state,inventory){return equippedItems(state,inventory).filter(item=>item.attunement).length;}
export function isTwoHanded(item){return Boolean(item?.attack?.properties?.includes("two-handed"));}
export function resolveWeaponAbility(item,abilities){if(!item?.attack)return null;if(item.attack.properties?.includes("finesse"))return abilityModifier(abilities.dexterity)>=abilityModifier(abilities.strength)?"dexterity":"strength";return item.attack.kind==="ranged"?"dexterity":(item.attack.attackAbility||"strength");}
export function itemUseAction(item,edition="2014"){const key=String(edition).includes("2024")?"dnd-2024":"dnd-2014";return item?.useActionByEdition?.[key]||null;}
function armorTraining(profile,item){return !item?.armorCategory||Boolean(profile?.armorTraining?.includes(item.armorCategory));}
export function canEquip(item,slot,state,inventory){if(!item||!validSlots(item).includes(slot))return{ok:false,reason:"That card does not fit this equipment slot."};if(item.category==="shield"){const otherShield=equippedItems(state,inventory).find(entry=>entry.category==="shield"&&entry.id!==item.id);if(otherShield)return{ok:false,reason:"Only one Shield can be used in the active loadout at a time."};}const replacing=state.equipped[slot]?inventory.find(entry=>entry.id===state.equipped[slot]):null;const next=attunementCount(state,inventory)-(replacing?.attunement?1:0)+(item.attunement&&!Object.values(state.equipped).includes(item.id)?1:0);return next>3?{ok:false,reason:"You cannot attune to more than three magic items."}:{ok:true};}
export function deriveStats(state,inventory,activeCharacter=characterCard){const profileKey=String(state.edition||"2014").includes("2024")?"dnd-2024":"dnd-2014";const rules2024=profileKey==="dnd-2024";const profile=activeCharacter.profiles?.[profileKey]||activeCharacter.profiles?.["dnd-2014"];const abilities={...(profile?.abilities||activeCharacter.base.abilities)};const level=profile?.level||3;const pb=proficiencyBonus(level);const saves={};for(const ability of ABILITIES)saves[ability]=profile?savingThrowModifier(profile,ability):activeCharacter.base.saves[ability];const stats={...activeCharacter.base,maxHp:profile?.maxHp??activeCharacter.base.maxHp,speed:profile?.speed??activeCharacter.base.speed,proficiency:pb,abilities,saves,ac:10+abilityModifier(abilities.dexterity),traits:[],attackProfile:null,attack:0,damage:0};const items=equippedItems(state,inventory);
 for(const item of items){if(item.strengthRequirement&&abilities.strength<item.strengthRequirement){stats.speed=Math.max(0,stats.speed-10);stats.traits.push(`Speed -10 ft.: ${item.name} requires Strength ${item.strengthRequirement}`);}if(item.armorCategory&&!armorTraining(profile,item)){stats.traits.push(`Untrained ${item.armorCategory}: Disadvantage on Strength/Dexterity D20 tests; cannot cast spells`);}for(const effect of item.effects){if(effect.kind!=="armorFormula")continue;const dex=abilityModifier(abilities.dexterity);const applied=effect.dexCap==null?dex:Math.min(dex,effect.dexCap);stats.ac=Math.max(stats.ac,effect.base+applied);}}
 for(const item of items){for(const effect of item.effects){if(effect.kind==="armorFormula"||effect.target==="attack"||effect.target==="damage")continue;if(effect.kind==="add"){if(item.category==="shield"&&rules2024&&!armorTraining(profile,item))continue;stats[effect.target]=(stats[effect.target]??0)+effect.value;}if(effect.kind==="allSaves")Object.keys(stats.saves).forEach(key=>stats.saves[key]+=effect.value);if(effect.kind==="trait")stats.traits.push(effect.label);if(effect.kind==="advantage")stats.traits.push(`Advantage: ${effect.target}`);}}
 const handWeaponIds=[state.equipped.mainHand,state.equipped.offHand].filter(Boolean);let activeWeapon=handWeaponIds.map(id=>inventory.find(entry=>entry.id===id)).find(item=>item?.attack)||null;
 if(activeWeapon){const ability=resolveWeaponAbility(activeWeapon,abilities);const mod=abilityModifier(abilities[ability]);const profileWeapon=profile?.attacks?.find(entry=>entry.id===activeWeapon.id||entry.id===activeWeapon.id.replace('-plus-1',''));const broadProficiency=profile?.weaponProficiencies?.includes(activeWeapon.attack.weaponGroup);const proficient=profileWeapon?.proficient??Boolean(broadProficiency);const attackMagic=activeWeapon.effects.filter(e=>e.kind==="add"&&e.target==="attack").reduce((n,e)=>n+e.value,0);const damageMagic=activeWeapon.effects.filter(e=>e.kind==="add"&&e.target==="damage").reduce((n,e)=>n+e.value,0);stats.attack=mod+(proficient?pb:0)+(profileWeapon?.fightingStyleAttackBonus||0)+attackMagic;stats.damage=mod+damageMagic;stats.attackProfile={...activeWeapon.attack,name:activeWeapon.name,attackAbility:ability,proficient,mastery:profileWeapon?.mastery||null};if(activeWeapon.attack.properties?.includes("heavy")){if(rules2024){const heavyScore=activeWeapon.attack.kind==="ranged"?abilities.dexterity:abilities.strength;if(heavyScore<13)stats.traits.push(`Disadvantage: Heavy ${activeWeapon.name} attacks require ${activeWeapon.attack.kind==="ranged"?"Dexterity":"Strength"} 13`);}else if(["small","tiny"].includes(String(profile?.size||"").toLowerCase()))stats.traits.push(`Disadvantage: ${profile.size} creature using Heavy ${activeWeapon.name}`);}}
 return stats;}
function clearTwoHandedGrip(state,inventory,slot,stowed){const existingId=state.equipped[slot];if(!existingId)return;const existing=inventory.find(entry=>entry.id===existingId);if(!isTwoHanded(existing))return;if(!stowed.includes(existingId))stowed.push(existingId);for(const hand of handSlots){if(state.equipped[hand]===existingId)state.equipped[hand]=null;}}
export function equipItem(state,inventory,itemId,slot){const item=inventory.find(entry=>entry.id===itemId);const check=canEquip(item,slot,state,inventory);if(!check.ok)return check;const stowed=[];for(const key of Object.keys(state.equipped)){if(state.equipped[key]===itemId)state.equipped[key]=null;}if(handSlots.includes(slot)){for(const hand of handSlots)clearTwoHandedGrip(state,inventory,hand,stowed);if(isTwoHanded(item)){for(const hand of handSlots){const occupied=state.equipped[hand];if(occupied&&!stowed.includes(occupied))stowed.push(occupied);state.equipped[hand]=itemId;}return{ok:true,stowed};}const occupied=state.equipped[slot];if(occupied&&!stowed.includes(occupied))stowed.push(occupied);state.equipped[slot]=itemId;return{ok:true,stowed};}state.equipped[slot]=itemId;return{ok:true,stowed};}
export function unequipItem(state,itemId){Object.keys(state.equipped).forEach(slot=>{if(state.equipped[slot]===itemId)state.equipped[slot]=null;});}
export function useItem(item){if(item.uses){if(item.uses.current<1)return{ok:false,reason:"No charges remain."};item.uses.current-=1;return{ok:true,text:`${item.uses.current}/${item.uses.max} charges remain.`};}if(item.consumable){if(item.consumable.count<1)return{ok:false,reason:"None remain."};item.consumable.count-=1;return{ok:true,text:`${item.consumable.count} remain.`};}return{ok:false,reason:"This item has no tracked use."};}
