import { defaultCharacterCard } from "./character-cards.js";
import { ABILITIES, abilityModifier, proficiencyBonus, savingThrowModifier } from "../dnd/rules-engine.js";
export const characterCard=defaultCharacterCard;
const srd=item=>Object.freeze({source:"SRD",color:"srd-item",...item});
const custom=item=>Object.freeze({source:"Wishing Cake",color:"custom-item",...item});
const weapon=(id,name,image,attack)=>srd({id,name,category:"weapon",rarity:"standard",image,validSlots:["mainHand"],attunement:false,edition:"2014/2024",front:name,playerText:`${attack.damageDice} ${attack.damageType}; ${attack.range}.`,dmText:"Use the loaded character profile for proficiency, ability modifier, Fighting Style, and 2024 mastery.",attack,effects:[]});
export const itemCards=Object.freeze([
 srd({id:"leather-armor",name:"Leather Armor",category:"armor",rarity:"standard",image:"🥋",validSlots:["armor"],attunement:false,edition:"2014/2024",front:"Supple leather armor",playerText:"AC 11 + Dexterity modifier.",dmText:"Light armor formula: 11 + Dexterity modifier.",effects:[{kind:"armorFormula",base:11,dexCap:null}]}),
 srd({id:"scale-mail",name:"Scale Mail",category:"armor",rarity:"standard",image:"🛡️",validSlots:["armor"],attunement:false,edition:"2014/2024",front:"Overlapping metal scales",playerText:"AC 14 + Dexterity modifier (maximum +2); disadvantage on Stealth.",dmText:"Medium armor formula: 14 + Dexterity modifier, maximum +2.",effects:[{kind:"armorFormula",base:14,dexCap:2},{kind:"trait",label:"Disadvantage: Stealth while wearing Scale Mail"}]}),
 srd({id:"chain-mail",name:"Chain Mail",category:"armor",rarity:"standard",image:"⛓️",validSlots:["armor"],attunement:false,edition:"2014/2024",front:"Interlocking heavy mail",playerText:"AC 16; Strength requirement 13; disadvantage on Stealth.",dmText:"Heavy armor sets AC to 16; Dexterity does not modify it.",effects:[{kind:"armorFormula",base:16,dexCap:0},{kind:"trait",label:"Disadvantage: Stealth while wearing Chain Mail"}]}),
 srd({id:"shield",name:"Shield",category:"shield",rarity:"standard",image:"🛡️",validSlots:["offHand"],attunement:false,edition:"2014/2024",front:"A sturdy shield",playerText:"While wielding this shield, gain +2 AC.",dmText:"Apply +2 AC while equipped. A two-handed weapon cannot be actively used at the same time.",effects:[{kind:"add",target:"ac",value:2}]}),
 weapon("rapier","Rapier","🗡️",{kind:"melee",attackAbility:"dexterity",damageDice:"1d8",damageType:"piercing",range:"5 ft.",properties:["finesse"],mastery2024:"Vex"}),
 weapon("shortsword","Shortsword","⚔️",{kind:"melee",attackAbility:"dexterity",damageDice:"1d6",damageType:"piercing",range:"5 ft.",properties:["finesse","light"],mastery2024:"Vex"}),
 weapon("dagger","Dagger","🔪",{kind:"melee",attackAbility:"dexterity",damageDice:"1d4",damageType:"piercing",range:"5 ft. / 20/60 ft.",properties:["finesse","light","thrown"],mastery2024:"Nick"}),
 weapon("mace","Mace","🔨",{kind:"melee",attackAbility:"strength",damageDice:"1d6",damageType:"bludgeoning",range:"5 ft.",properties:[],mastery2024:"Sap"}),
 weapon("longbow","Longbow","🏹",{kind:"ranged",attackAbility:"dexterity",damageDice:"1d8",damageType:"piercing",range:"150/600 ft.",properties:["ammunition","heavy","two-handed"],mastery2024:"Slow"}),
 weapon("shortbow","Shortbow","🏹",{kind:"ranged",attackAbility:"dexterity",damageDice:"1d6",damageType:"piercing",range:"80/320 ft.",properties:["ammunition","two-handed"],mastery2024:"Vex"}),
 custom({id:"birthday-spark",name:"Birthday Spark Candle",category:"wondrous",rarity:"story",image:"🕯️",validSlots:["wondrous"],attunement:false,edition:"Adventure",front:"A warm candle-flame token",playerText:"After a failed check, spend one charge to add 1d4 to the roll.",dmText:"Adventure-specific story item. Three charges; refresh all charges in the Cake Chamber.",uses:{max:3,current:3,recharge:"Cake Chamber"},effects:[]}),
 custom({id:"keeper-crown",name:"Keeper of the Wish Crown",category:"wondrous",rarity:"story",image:"👑",validSlots:["head"],attunement:false,edition:"Adventure",front:"A paper crown marked KEEPER OF THE WISH",playerText:"Narrative item; no numerical bonus.",dmText:"Do not modify ability scores, saves, AC, attacks, or damage.",effects:[{kind:"trait",label:"Birthday heart"}]})
]);
export const slotLabels=Object.freeze({head:"Head",neck:"Neck",shoulders:"Shoulders",armor:"Armor",hands:"Hands",mainHand:"Main Hand",offHand:"Off Hand",ring1:"Ring 1",ring2:"Ring 2",feet:"Feet",wondrous:"Wondrous"});
export function createInventory(ownedIds=null){const allowed=ownedIds?new Set(ownedIds):null;return itemCards.filter(item=>!allowed||allowed.has(item.id)).map(item=>({...item,effects:item.effects.map(effect=>({...effect})),attack:item.attack?{...item.attack,properties:[...(item.attack.properties||[])]}:null,uses:item.uses?{...item.uses}:null,consumable:item.consumable?{...item.consumable}:null}));}
export function validSlots(item){return item?.validSlots??[];}
export function equippedItems(state,inventory){return Object.values(state.equipped).filter(Boolean).map(id=>inventory.find(item=>item.id===id)).filter(Boolean);}
export function attunementCount(state,inventory){return equippedItems(state,inventory).filter(item=>item.attunement).length;}
export function canEquip(item,slot,state,inventory){if(!item||!validSlots(item).includes(slot))return{ok:false,reason:"That card does not fit this equipment slot."};const replacing=state.equipped[slot]?inventory.find(entry=>entry.id===state.equipped[slot]):null;const next=attunementCount(state,inventory)-(replacing?.attunement?1:0)+(item.attunement&&!Object.values(state.equipped).includes(item.id)?1:0);return next>3?{ok:false,reason:"You cannot attune to more than three magic items."}:{ok:true};}
export function deriveStats(state,inventory,activeCharacter=characterCard){const profileKey=String(state.edition||"2014").includes("2024")?"dnd-2024":"dnd-2014";const profile=activeCharacter.profiles?.[profileKey]||activeCharacter.profiles?.["dnd-2014"];const abilities={...(profile?.abilities||activeCharacter.base.abilities)};const level=profile?.level||3;const pb=proficiencyBonus(level);const saves={};for(const ability of ABILITIES)saves[ability]=profile?savingThrowModifier(profile,ability):activeCharacter.base.saves[ability];const stats={...activeCharacter.base,maxHp:profile?.maxHp??activeCharacter.base.maxHp,speed:profile?.speed??activeCharacter.base.speed,proficiency:pb,abilities,saves,ac:10+abilityModifier(abilities.dexterity),traits:[],attackProfile:null,attack:0,damage:0};const items=equippedItems(state,inventory);
 for(const item of items){for(const effect of item.effects){if(effect.kind!=="armorFormula")continue;const dex=abilityModifier(abilities.dexterity);const applied=effect.dexCap==null?dex:Math.min(dex,effect.dexCap);stats.ac=Math.max(stats.ac,effect.base+applied);}}
 for(const item of items){for(const effect of item.effects){if(effect.kind==="armorFormula")continue;if(effect.kind==="add")stats[effect.target]=(stats[effect.target]??0)+effect.value;if(effect.kind==="allSaves")Object.keys(stats.saves).forEach(key=>stats.saves[key]+=effect.value);if(effect.kind==="trait")stats.traits.push(effect.label);if(effect.kind==="advantage")stats.traits.push(`Advantage: ${effect.target}`);}if(item.attack){const ability=item.attack.attackAbility||"strength";const mod=abilityModifier(abilities[ability]);const profileWeapon=profile?.attacks?.find(entry=>entry.id===item.id);stats.attack=mod+pb+(profileWeapon?.fightingStyleAttackBonus||0);stats.damage=mod;stats.attackProfile={...item.attack,name:item.name,mastery:profileWeapon?.mastery||null};}}
 return stats;}
export function equipItem(state,inventory,itemId,slot){const item=inventory.find(entry=>entry.id===itemId);const check=canEquip(item,slot,state,inventory);if(!check.ok)return check;Object.keys(state.equipped).forEach(key=>{if(state.equipped[key]===itemId)state.equipped[key]=null;});const stowed=[];if(slot==="mainHand"&&item.attack?.properties?.includes("two-handed")&&state.equipped.offHand){stowed.push(state.equipped.offHand);state.equipped.offHand=null;}if(slot==="offHand"){const main=inventory.find(entry=>entry.id===state.equipped.mainHand);if(main?.attack?.properties?.includes("two-handed")){stowed.push(state.equipped.mainHand);state.equipped.mainHand=null;}}state.equipped[slot]=itemId;return{ok:true,stowed};}
export function unequipItem(state,itemId){Object.keys(state.equipped).forEach(slot=>{if(state.equipped[slot]===itemId)state.equipped[slot]=null;});}
export function useItem(item){if(item.uses){if(item.uses.current<1)return{ok:false,reason:"No charges remain."};item.uses.current-=1;return{ok:true,text:`${item.uses.current}/${item.uses.max} charges remain.`};}if(item.consumable){if(item.consumable.count<1)return{ok:false,reason:"None remain."};item.consumable.count-=1;return{ok:true,text:`${item.consumable.count} remain.`};}return{ok:false,reason:"This item has no tracked use."};}
