const freeze = value => Object.freeze(value);
const deepFreeze = value => {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.values(value).forEach(deepFreeze);
  return Object.freeze(value);
};

const emptyEquipment = () => ({head:null,neck:null,shoulders:null,armor:null,hands:null,mainHand:null,offHand:null,ring1:null,ring2:null,feet:null,wondrous:"birthday-spark"});
const qr = (id, edition) => `player.html?character=${id}&edition=${edition}`;
const card = value => deepFreeze(value);

const rogueAbilities = {strength:8,dexterity:16,constitution:14,intelligence:12,wisdom:12,charisma:10};
const rogueAttacks = [
  {id:"shortsword",name:"Shortsword",kind:"melee",attackAbility:"dexterity",proficient:true,damageDice:"1d6",damageType:"piercing",range:"5 ft.",properties:["finesse","light"]},
  {id:"shortbow",name:"Shortbow",kind:"ranged",attackAbility:"dexterity",proficient:true,damageDice:"1d6",damageType:"piercing",range:"80/320 ft.",properties:["ammunition","two-handed"]}
];
const rogue2014 = {
  rulesId:"dnd-2014",source:"SRD 5.1 / 2014 fifth-edition rules",level:3,className:"Rogue",subclass:"Thief",species:"Lightfoot Halfling",background:"Criminal",size:"Small",speed:25,
  abilities:rogueAbilities,hitDie:"d8",maxHp:24,hitDice:{total:3,remaining:3,die:"d8"},saveProficiencies:["dexterity","intelligence"],
  skillProficiencies:["acrobatics","deception","investigation","perception","sleightOfHand","stealth"],expertise:["perception","stealth"],armorTraining:["Light armor"],weaponProficiencies:["Simple weapons","Hand crossbows","Longswords","Rapiers","Shortswords"],tools:["Thieves’ tools","One gaming set"],languages:["Common","Halfling"],senses:[],criticalRange:[20],initiative:{modifier:3,advantage:false},attacks:rogueAttacks.map(x=>({...x,mastery:null})),
  resources:[{id:"sneak-attack",name:"Sneak Attack",max:1,recharge:"Each turn",action:"On a qualifying hit",effect:"Deal an extra 2d6 damage once per turn."}],
  features:[
    {name:"Expertise",source:"Rogue 1",summary:"Double proficiency bonus for Perception and Stealth checks."},{name:"Sneak Attack",source:"Rogue 1",summary:"Once per turn, deal 2d6 extra damage with a finesse or ranged weapon when the attack qualifies."},{name:"Cunning Action",source:"Rogue 2",summary:"Use a Bonus Action to Dash, Disengage, or Hide."},{name:"Fast Hands",source:"Thief 3",summary:"Use Cunning Action for Sleight of Hand, thieves’ tools to open a lock/disarm a trap, or Use an Object."},{name:"Second-Story Work",source:"Thief 3",summary:"Climbing no longer costs extra movement; running jumps gain Dexterity modifier distance."},{name:"Lucky",source:"Halfling",summary:"When you roll a 1 on an attack roll, ability check, or saving throw, reroll the die."}
  ],originNotes:["2014 halfling racial ability increases are included in the listed final scores."],equipmentNotes:["Leather armor, shortsword, shortbow, arrows, thieves’ tools, and burglar’s gear."],spellcastingAbility:null,spellSlots:{},spells:[]
};
const rogue2024 = {
  ...rogue2014,rulesId:"dnd-2024",source:"SRD 5.2.1 / 2024 fifth-edition rules",species:"Halfling",background:"Criminal",speed:30,
  attacks:rogueAttacks.map(x=>({...x,mastery:x.id==="shortsword"?"Vex":"Vex"})),weaponMasteries:["Shortsword — Vex","Shortbow — Vex"],originFeats:["Alert"],
  features:[
    {name:"Expertise",source:"Rogue 1",summary:"Double proficiency bonus for Perception and Stealth checks."},{name:"Sneak Attack",source:"Rogue 1",summary:"Once per turn, deal 2d6 extra damage with a Finesse or Ranged weapon when the attack qualifies."},{name:"Weapon Mastery",source:"Rogue 1",summary:"Use the mastery properties of two chosen weapons; Shortsword and Shortbow are selected."},{name:"Cunning Action",source:"Rogue 2",summary:"Use a Bonus Action to Dash, Disengage, or Hide."},{name:"Fast Hands",source:"Thief 3",summary:"As a Bonus Action, pick a lock/disarm a trap with thieves’ tools, pick a pocket, or take the Utilize action."},{name:"Second-Story Work",source:"Thief 3",summary:"Gain a Climb Speed equal to Speed and use Dexterity rather than Strength to determine jump distance."},{name:"Alert",source:"Criminal",summary:"Add proficiency bonus to Initiative and, after rolling Initiative, you can swap with a willing ally."}
  ],initiative:{modifier:5,advantage:false},originNotes:["2024 Criminal grants Alert; final ability scores include background increases."],equipmentNotes:["Leather armor, shortsword, shortbow, arrows, thieves’ tools, and burglar’s gear."]
};

const wizardAbilities={strength:8,dexterity:14,constitution:14,intelligence:16,wisdom:12,charisma:10};
const wizardAttack=[{id:"dagger",name:"Dagger",kind:"melee",attackAbility:"dexterity",proficient:true,damageDice:"1d4",damageType:"piercing",range:"5 ft. / 20/60 ft.",properties:["finesse","light","thrown"]}];
const wizardSpells=["Fire Bolt","Ray of Frost","Mage Hand","Magic Missile","Shield","Mage Armor","Thunderwave","Detect Magic","Misty Step","Scorching Ray","Web"];
const wizard2014={rulesId:"dnd-2014",source:"SRD 5.1 / 2014 fifth-edition rules",level:3,className:"Wizard",subclass:"School of Evocation",species:"High Elf",background:"Sage",size:"Medium",speed:30,abilities:wizardAbilities,hitDie:"d6",maxHp:20,hitDice:{total:3,remaining:3,die:"d6"},saveProficiencies:["intelligence","wisdom"],skillProficiencies:["arcana","history","investigation","perception"],expertise:[],armorTraining:[],weaponProficiencies:["Daggers","Darts","Slings","Quarterstaffs","Light crossbows"],tools:[],languages:["Common","Elvish","Draconic","Dwarvish"],senses:["Darkvision 60 ft."],criticalRange:[20],initiative:{modifier:2,advantage:false},attacks:wizardAttack.map(x=>({...x,mastery:null})),resources:[{id:"arcane-recovery",name:"Arcane Recovery",max:1,recharge:"Long Rest",action:"After a Short Rest",effect:"Recover expended spell slots with combined level up to 2."}],features:[{name:"Arcane Recovery",source:"Wizard 1",summary:"Once per day after a Short Rest, recover spell slots totaling up to half Wizard level rounded up."},{name:"Evocation Savant",source:"Evocation 2",summary:"Copying Evocation spells into the spellbook costs half the normal gold and time."},{name:"Sculpt Spells",source:"Evocation 2",summary:"When an Evocation spell affects other creatures you can see, protect 1 + spell level of them from its saving-throw damage."}],originNotes:["2014 High Elf ability increases are included in the listed final scores."],equipmentNotes:["Spellbook, arcane focus, dagger, scholar’s pack."],spellcastingAbility:"intelligence",spellSlots:{1:4,2:2},spells:wizardSpells};
const wizard2024={...wizard2014,rulesId:"dnd-2024",source:"SRD 5.2.1 / 2024 fifth-edition rules",species:"Elf",background:"Sage",weaponMasteries:[],originFeats:["Magic Initiate (Wizard)"],resources:[{id:"arcane-recovery",name:"Arcane Recovery",max:1,recharge:"Long Rest",action:"Short Rest",effect:"Recover expended spell slots with combined level up to 2."}],features:[{name:"Ritual Adept",source:"Wizard 1",summary:"Cast any Ritual-tagged Wizard spell in the spellbook as a ritual without preparing it."},{name:"Arcane Recovery",source:"Wizard 1",summary:"After a Short Rest, recover spell slots totaling up to half Wizard level rounded up; once per Long Rest."},{name:"Scholar",source:"Wizard 2",summary:"Choose one scholarly skill proficiency and gain Expertise in it; Arcana is selected."},{name:"Evocation Savant",source:"Evoker 3",summary:"Add two Evocation spells of level 2 or lower to the spellbook for free."},{name:"Potent Cantrip",source:"Evoker 3",summary:"Damaging cantrips still affect creatures that avoid the brunt of the effect according to the 2024 Evoker feature."}],expertise:["arcana"],originNotes:["2024 Sage grants Magic Initiate (Wizard); final ability scores include background increases."],equipmentNotes:["Spellbook, arcane focus, dagger, scholar’s pack."]};

const clericAbilities={strength:14,dexterity:10,constitution:14,intelligence:10,wisdom:16,charisma:12};
const clericAttacks=[{id:"mace",name:"Mace",kind:"melee",attackAbility:"strength",proficient:true,damageDice:"1d6",damageType:"bludgeoning",range:"5 ft.",properties:[]}];
const clericSpells=["Guidance","Sacred Flame","Thaumaturgy","Bless","Cure Wounds","Healing Word","Guiding Bolt","Sanctuary","Lesser Restoration","Spiritual Weapon","Aid"];
const cleric2014={rulesId:"dnd-2014",source:"SRD 5.1 / 2014 fifth-edition rules",level:3,className:"Cleric",subclass:"Life Domain",species:"Hill Dwarf",background:"Acolyte",size:"Medium",speed:25,abilities:clericAbilities,hitDie:"d8",maxHp:27,hitDice:{total:3,remaining:3,die:"d8"},saveProficiencies:["wisdom","charisma"],skillProficiencies:["insight","medicine","religion"],expertise:[],armorTraining:["Light armor","Medium armor","Heavy armor","Shields"],weaponProficiencies:["Simple weapons"],tools:["Brewer’s supplies"],languages:["Common","Dwarvish","Celestial"],senses:["Darkvision 60 ft."],criticalRange:[20],initiative:{modifier:0,advantage:false},attacks:clericAttacks.map(x=>({...x,mastery:null})),resources:[{id:"channel-divinity",name:"Channel Divinity",max:1,recharge:"Short or Long Rest",action:"Action",effect:"Use Turn Undead or Preserve Life."}],features:[{name:"Disciple of Life",source:"Life Domain 1",summary:"Healing spells of 1st level or higher restore additional hit points equal to 2 + the spell’s level."},{name:"Channel Divinity — Turn Undead",source:"Cleric 2",summary:"Present holy symbol; Undead that fail the Wisdom save are turned."},{name:"Channel Divinity — Preserve Life",source:"Life Domain 2",summary:"Restore up to 15 HP divided among creatures within 30 feet, not above half maximum HP."}],originNotes:["2014 Hill Dwarf durability is included in max HP."],equipmentNotes:["Chain mail, shield, mace, holy symbol, priest’s pack."],spellcastingAbility:"wisdom",spellSlots:{1:4,2:2},spells:clericSpells};
const cleric2024={...cleric2014,rulesId:"dnd-2024",source:"SRD 5.2.1 / 2024 fifth-edition rules",species:"Dwarf",background:"Acolyte",speed:30,maxHp:24,armorTraining:["Light armor","Medium armor","Heavy armor","Shields"],weaponProficiencies:["Simple weapons","Martial weapons"],originFeats:["Magic Initiate (Cleric)"],resources:[{id:"channel-divinity",name:"Channel Divinity",max:2,recharge:"1 use on Short Rest; all on Long Rest",action:"Varies",effect:"Use Divine Spark, Turn Undead, or Preserve Life."}],features:[{name:"Divine Order — Protector",source:"Cleric 1",summary:"Gain martial weapon proficiency and Heavy armor training."},{name:"Channel Divinity — Divine Spark",source:"Cleric 2",summary:"Expend Channel Divinity to heal an ally or damage an enemy with divine energy."},{name:"Turn Undead",source:"Cleric 2",summary:"Expend Channel Divinity to turn Undead that fail the save."},{name:"Disciple of Life",source:"Life Domain 3",summary:"When a spell-slot spell restores HP, increase the healing on the turn you cast it."},{name:"Preserve Life",source:"Life Domain 3",summary:"Expend Channel Divinity to restore hit points to nearby creatures using the Life Domain feature."}],originNotes:["2024 Acolyte grants Magic Initiate (Cleric); final ability scores include background increases."],equipmentNotes:["Chain mail, shield, mace, holy symbol, priest’s pack."]};

const rangerAbilities={strength:10,dexterity:16,constitution:14,intelligence:10,wisdom:14,charisma:10};
const rangerAttacks=[{id:"longbow",name:"Longbow",kind:"ranged",attackAbility:"dexterity",proficient:true,fightingStyleAttackBonus:2,damageDice:"1d8",damageType:"piercing",range:"150/600 ft.",properties:["ammunition","heavy","two-handed"]},{id:"shortsword",name:"Shortsword",kind:"melee",attackAbility:"dexterity",proficient:true,damageDice:"1d6",damageType:"piercing",range:"5 ft.",properties:["finesse","light"]}];
const ranger2014={rulesId:"dnd-2014",source:"SRD 5.1 / 2014 fifth-edition rules",level:3,className:"Ranger",subclass:"Hunter",species:"Wood Elf",background:"Outlander",size:"Medium",speed:35,abilities:rangerAbilities,hitDie:"d10",maxHp:28,hitDice:{total:3,remaining:3,die:"d10"},saveProficiencies:["strength","dexterity"],skillProficiencies:["animalHandling","athletics","nature","perception","stealth","survival"],expertise:[],armorTraining:["Light armor","Medium armor","Shields"],weaponProficiencies:["Simple weapons","Martial weapons"],tools:["One musical instrument"],languages:["Common","Elvish","Goblin"],senses:["Darkvision 60 ft."],fightingStyle:{name:"Archery",summary:"+2 bonus to attack rolls made with ranged weapons."},criticalRange:[20],initiative:{modifier:3,advantage:false},attacks:rangerAttacks.map(x=>({...x,mastery:null})),resources:[{id:"hunter-mark",name:"Hunter’s Mark",max:3,recharge:"Spell slots",action:"Bonus Action",effect:"Concentration; marked target takes +1d6 damage when you hit it with a weapon attack."}],features:[{name:"Favored Enemy",source:"Ranger 1",summary:"Advantage on Survival checks to track the chosen favored enemies and Intelligence checks to recall information about them."},{name:"Natural Explorer",source:"Ranger 1",summary:"Gain exploration benefits in a chosen favored terrain."},{name:"Fighting Style — Archery",source:"Ranger 2",summary:"Add +2 to ranged weapon attack rolls."},{name:"Spellcasting",source:"Ranger 2",summary:"Cast Ranger spells using Wisdom."},{name:"Primeval Awareness",source:"Ranger 3",summary:"Expend a spell slot to sense certain creature types within range."},{name:"Colossus Slayer",source:"Hunter 3",summary:"Once per turn, when a weapon attack hits a creature below its HP maximum, deal an extra 1d8 damage."}],originNotes:["2014 Wood Elf speed and ability increases are included."],equipmentNotes:["Longbow, shortswords, medium armor, explorer’s pack."],spellcastingAbility:"wisdom",spellSlots:{1:3},spells:["Hunter’s Mark","Cure Wounds","Goodberry"]};
const ranger2024={...ranger2014,rulesId:"dnd-2024",source:"SRD 5.2.1 / 2024 fifth-edition rules",species:"Elf",background:"Guide",speed:30,attacks:rangerAttacks.map(x=>({...x,mastery:x.id==="longbow"?"Slow":"Vex"})),weaponMasteries:["Longbow — Slow","Shortsword — Vex"],originFeats:["Magic Initiate (Druid)"],resources:[{id:"favored-enemy",name:"Favored Enemy — Hunter’s Mark",max:2,recharge:"Long Rest",action:"Bonus Action",effect:"Hunter’s Mark is always prepared and can be cast twice without a spell slot."}],features:[{name:"Favored Enemy",source:"Ranger 1",summary:"Hunter’s Mark is always prepared and can be cast twice per Long Rest without a spell slot."},{name:"Weapon Mastery",source:"Ranger 1",summary:"Use mastery properties of two chosen weapons."},{name:"Deft Explorer",source:"Ranger 2",summary:"Gain Expertise in one skill and learn two additional languages."},{name:"Fighting Style — Archery",source:"Ranger 2",summary:"Add +2 to ranged weapon attack rolls."},{name:"Hunter’s Lore",source:"Hunter 3",summary:"While a creature is marked by Hunter’s Mark, learn its immunities, resistances, and vulnerabilities."},{name:"Hunter’s Prey — Colossus Slayer",source:"Hunter 3",summary:"Once per turn, deal an extra 1d8 damage to a creature already missing HP when you hit it with a weapon."}],expertise:["survival"],languages:["Common","Elvish","Goblin","Sylvan"],originNotes:["2024 Guide grants Magic Initiate (Druid); final scores include background increases."],equipmentNotes:["Longbow, shortswords, medium armor, explorer’s pack."],spellSlots:{1:3},spells:["Hunter’s Mark","Cure Wounds","Goodberry","Ensnaring Strike"]};

const bardAbilities={strength:8,dexterity:14,constitution:14,intelligence:12,wisdom:10,charisma:16};
const bardAttacks=[{id:"rapier",name:"Rapier",kind:"melee",attackAbility:"dexterity",proficient:true,damageDice:"1d8",damageType:"piercing",range:"5 ft.",properties:["finesse"]}];
const bardSpells=["Vicious Mockery","Mage Hand","Healing Word","Dissonant Whispers","Faerie Fire","Thunderwave","Detect Magic","Suggestion","Shatter"];
const bard2014={rulesId:"dnd-2014",source:"SRD 5.1 / 2014 fifth-edition rules",level:3,className:"Bard",subclass:"College of Lore",species:"Half-Elf",background:"Entertainer",size:"Medium",speed:30,abilities:bardAbilities,hitDie:"d8",maxHp:24,hitDice:{total:3,remaining:3,die:"d8"},saveProficiencies:["dexterity","charisma"],skillProficiencies:["acrobatics","deception","history","insight","perception","performance","persuasion","sleightOfHand"],expertise:["performance","persuasion"],armorTraining:["Light armor"],weaponProficiencies:["Simple weapons","Hand crossbows","Longswords","Rapiers","Shortswords"],tools:["Lute","Flute","Drum","Disguise kit"],languages:["Common","Elvish","Dwarvish"],senses:["Darkvision 60 ft."],criticalRange:[20],initiative:{modifier:2,advantage:false},attacks:bardAttacks.map(x=>({...x,mastery:null})),resources:[{id:"bardic-inspiration",name:"Bardic Inspiration",max:3,recharge:"Long Rest",action:"Bonus Action",effect:"Give one creature a d6 Bardic Inspiration die."}],features:[{name:"Bardic Inspiration d6",source:"Bard 1",summary:"Bonus Action; grant a creature a d6 it can add to an ability check, attack roll, or saving throw."},{name:"Jack of All Trades",source:"Bard 2",summary:"Add half proficiency bonus to ability checks that do not already include proficiency."},{name:"Song of Rest d6",source:"Bard 2",summary:"During a Short Rest, allies who spend Hit Dice regain an extra 1d6 HP."},{name:"Expertise",source:"Bard 3",summary:"Double proficiency bonus for Performance and Persuasion."},{name:"Bonus Proficiencies",source:"College of Lore 3",summary:"Gain proficiency in three additional skills."},{name:"Cutting Words",source:"College of Lore 3",summary:"Reaction; expend Bardic Inspiration to subtract the d6 from a visible creature’s attack roll, ability check, or damage roll."}],originNotes:["2014 Half-Elf ability increases are included in final scores."],equipmentNotes:["Leather armor, rapier, lute, diplomat/entertainer gear."],spellcastingAbility:"charisma",spellSlots:{1:4,2:2},spells:bardSpells};
const bard2024={...bard2014,rulesId:"dnd-2024",source:"SRD 5.2.1 / 2024 fifth-edition rules",species:"Human",background:"Entertainer",weaponProficiencies:["Simple weapons"],originFeats:["Musician","Skilled"],resources:[{id:"bardic-inspiration",name:"Bardic Inspiration",max:3,recharge:"Long Rest",action:"Bonus Action",effect:"Give a creature a d6 Bardic Inspiration die; use follows the 2024 Bard feature."}],features:[{name:"Bardic Inspiration d6",source:"Bard 1",summary:"Bonus Action; grant a creature a d6 Bardic Inspiration die."},{name:"Jack of All Trades",source:"Bard 2",summary:"Add half proficiency bonus to ability checks that do not use proficiency."},{name:"Expertise",source:"Bard 2",summary:"Double proficiency bonus for Performance and Persuasion."},{name:"Bonus Proficiencies",source:"College of Lore 3",summary:"Gain proficiency in three additional skills."},{name:"Cutting Words",source:"College of Lore 3",summary:"Reaction; expend Bardic Inspiration after a creature within 60 feet succeeds on an ability check or attack roll, or makes a damage roll, and subtract the d6."},{name:"Musician",source:"Entertainer",summary:"After a Short or Long Rest, inspire allies according to the 2024 Origin feat."}],originNotes:["2024 Entertainer grants Musician; Human Versatile grants Skilled."],equipmentNotes:["Leather armor, rapier purchased with starting gold, lute, entertainer gear."]};

export const additionalPregens = Object.freeze([
  card({id:"merrin-thief",version:"1.0.0",compatibleSystems:["dnd-2014","dnd-2024"],adventureId:"wishing-cake",name:"Merrin Quickstep",classLine:"Rogue 3 · Thief",front:{title:"Merrin Quickstep",subtitle:"Trapbreaker & Scout",portrait:"🗝️",artAlt:"A quick halfling rogue with a shortbow, lockpicks, and a bright birthday sash."},back:{summary:"Mobile scout, trap specialist, and precision striker.",playNotes:["Use Sneak Attack once per turn when it qualifies.","Use Cunning Action to reposition.","Merrin is the party’s strongest lock-and-trap specialist."],importCodes:{"dnd-2014":"WC-MERRIN-R3-14","dnd-2024":"WC-MERRIN-R3-24"},qrPaths:{"dnd-2014":qr("merrin-thief","2014"),"dnd-2024":qr("merrin-thief","2024")}},profiles:{"dnd-2014":rogue2014,"dnd-2024":rogue2024},base:{maxHp:24,baseAc:13,speed:25,proficiency:2,attack:5,damage:3,abilities:rogueAbilities,saves:{strength:-1,dexterity:5,constitution:2,intelligence:3,wisdom:1,charisma:0}},features:["Rogue 3 — see complete edition-specific sheet."],startingEquipment:{...emptyEquipment(),armor:"leather-armor",mainHand:"shortsword"},ownedItemIds:["leather-armor","shortsword","shortbow","dagger","birthday-spark"]}),
  card({id:"elara-evoker",version:"1.0.0",compatibleSystems:["dnd-2014","dnd-2024"],adventureId:"wishing-cake",name:"Elara Starling",classLine:"Wizard 3 · Evoker",front:{title:"Elara Starling",subtitle:"Arcane Artillery",portrait:"✨",artAlt:"An elven wizard in midnight robes holding a glowing spellbook while sparks form birthday stars."},back:{summary:"Area-control and ranged spell specialist with a complete spellbook loadout.",playNotes:["Spell save DC 13 and spell attack +5.","Protect allies with the edition-appropriate Evoker feature.","Track 4 first-level and 2 second-level spell slots."],importCodes:{"dnd-2014":"WC-ELARA-W3-14","dnd-2024":"WC-ELARA-W3-24"},qrPaths:{"dnd-2014":qr("elara-evoker","2014"),"dnd-2024":qr("elara-evoker","2024")}},profiles:{"dnd-2014":wizard2014,"dnd-2024":wizard2024},base:{maxHp:20,baseAc:12,speed:30,proficiency:2,attack:4,damage:2,abilities:wizardAbilities,saves:{strength:-1,dexterity:2,constitution:2,intelligence:5,wisdom:3,charisma:0}},features:["Wizard 3 — see complete edition-specific sheet."],startingEquipment:{...emptyEquipment(),mainHand:"dagger"},ownedItemIds:["dagger","birthday-spark"]}),
  card({id:"brunna-life-cleric",version:"1.0.0",compatibleSystems:["dnd-2014","dnd-2024"],adventureId:"wishing-cake",name:"Brunna Hearthkeeper",classLine:"Cleric 3 · Life Domain",front:{title:"Brunna Hearthkeeper",subtitle:"Healer & Defender",portrait:"☀️",artAlt:"A stout dwarf cleric with a sun-marked shield, mace, and warm golden healing light."},back:{summary:"Durable frontline healer and divine support character.",playNotes:["Spell save DC 13 and spell attack +5.","Use Bless early when concentration is safe.","Preserve Life is a Channel Divinity option, not a spell slot."],importCodes:{"dnd-2014":"WC-BRUNNA-C3-14","dnd-2024":"WC-BRUNNA-C3-24"},qrPaths:{"dnd-2014":qr("brunna-life-cleric","2014"),"dnd-2024":qr("brunna-life-cleric","2024")}},profiles:{"dnd-2014":cleric2014,"dnd-2024":cleric2024},base:{maxHp:27,baseAc:10,speed:25,proficiency:2,attack:4,damage:2,abilities:clericAbilities,saves:{strength:2,dexterity:0,constitution:2,intelligence:0,wisdom:5,charisma:3}},features:["Life Cleric 3 — see complete edition-specific sheet."],startingEquipment:{...emptyEquipment(),armor:"chain-mail",mainHand:"mace",offHand:"shield"},ownedItemIds:["chain-mail","mace","shield","birthday-spark"]}),
  card({id:"fern-hunter",version:"1.0.0",compatibleSystems:["dnd-2014","dnd-2024"],adventureId:"wishing-cake",name:"Fern Greenbough",classLine:"Ranger 3 · Hunter",front:{title:"Fern Greenbough",subtitle:"Hunter & Wilderness Guide",portrait:"🏹",artAlt:"An elven ranger drawing a longbow decorated with green ribbon and small birthday charms."},back:{summary:"Ranged striker, tracker, and exploration specialist.",playNotes:["Longbow is +7 to hit with Archery and deals 1d8+3 piercing.","Hunter’s Mark and Colossus Slayer are separate damage riders.","Use the 2014 and 2024 Hunter features exactly as shown on the loaded sheet."],importCodes:{"dnd-2014":"WC-FERN-RG3-14","dnd-2024":"WC-FERN-RG3-24"},qrPaths:{"dnd-2014":qr("fern-hunter","2014"),"dnd-2024":qr("fern-hunter","2024")}},profiles:{"dnd-2014":ranger2014,"dnd-2024":ranger2024},base:{maxHp:28,baseAc:13,speed:35,proficiency:2,attack:5,damage:3,abilities:rangerAbilities,saves:{strength:2,dexterity:5,constitution:2,intelligence:0,wisdom:2,charisma:0}},features:["Hunter Ranger 3 — see complete edition-specific sheet."],startingEquipment:{...emptyEquipment(),armor:"scale-mail",mainHand:"longbow"},ownedItemIds:["scale-mail","longbow","shortsword","birthday-spark"]}),
  card({id:"lute-lore-bard",version:"1.0.0",compatibleSystems:["dnd-2014","dnd-2024"],adventureId:"wishing-cake",name:"Lute Bellweather",classLine:"Bard 3 · College of Lore",front:{title:"Lute Bellweather",subtitle:"Support, Face & Lorekeeper",portrait:"🎵",artAlt:"A smiling human bard with a lute, bright coat, rapier, and ribbons swirling into musical notes."},back:{summary:"Flexible support caster, social specialist, and skill expert.",playNotes:["Spell save DC 13 and spell attack +5.","Bardic Inspiration and Cutting Words share the same Inspiration resource.","Use Healing Word to recover a fallen ally at range."],importCodes:{"dnd-2014":"WC-LUTE-B3-14","dnd-2024":"WC-LUTE-B3-24"},qrPaths:{"dnd-2014":qr("lute-lore-bard","2014"),"dnd-2024":qr("lute-lore-bard","2024")}},profiles:{"dnd-2014":bard2014,"dnd-2024":bard2024},base:{maxHp:24,baseAc:12,speed:30,proficiency:2,attack:4,damage:2,abilities:bardAbilities,saves:{strength:-1,dexterity:4,constitution:2,intelligence:1,wisdom:0,charisma:5}},features:["Lore Bard 3 — see complete edition-specific sheet."],startingEquipment:{...emptyEquipment(),armor:"leather-armor",mainHand:"rapier"},ownedItemIds:["leather-armor","rapier","dagger","birthday-spark"]})
]);
